# Generated by Django 2.0.7 on 2019-01-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('펀드코드', models.CharField(db_index=True, max_length=5)),
                ('펀드명', models.CharField(db_index=True, max_length=150)),
                ('펀드설정일', models.DateTimeField(auto_now=True)),
                ('펀드순자산총액', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
    ]
